name: CI for React Project
on:
  push:
    branches:
      - main
      - development
      - release
  pull_request:
    branches:
      - main
      - development
      - release

jobs:
  build-and-test:
    runs-on: ubuntu-latest
